name: Go

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go mod download

      - name: Unit tests
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out

  autotag:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: autotag
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-commit: "true"
          output-file: "false"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.autotag.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.autotag.outputs.tag }}
          release_name: ${{ steps.autotag.outputs.tag }}
          body: ${{ steps.autotag.outputs.clean_changelog }}
